{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "demo-app-go.fullname" . }}
  labels:
    {{- include "demo-app-go.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "demo-app-go.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.targetPort }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}