apiVersion: v1
kind: ConfigMap
metadata:
  name: go-app-config
data:
  config.yml: |
    api:
      port: "8080"
      mode: "production"
    
    logger:
      logger: "logrus"
      app-name: "demo-app-go"
      log-method: "N"
      log-level: Debug
      log-format: JSON