apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yml
  - deployment.yml
  - service.yml
  - route.yml

commonLabels:
  app.kubernetes.io/managed-by: gitops
  app.kubernetes.io/instance: demo
  app.kubernetes.io/name: demo-app-go
